#!/usr/bin/env bash
# Install agents from this repo into a Claude Code agents directory.
#
#   ./install.sh                     copy all agents to ~/.claude/agents
#   ./install.sh --link              symlink instead (updates with `git pull`)
#   ./install.sh --project DIR       install into DIR/.claude/agents instead
#   ./install.sh --category review   only one category (repeatable)
#   ./install.sh --only a,b,c        only the named agents
#   ./install.sh --no-routing        skip writing agent-routing.md (see below)
#   ./install.sh --dry-run           show what would happen
#   ./install.sh --uninstall         remove agents that came from this repo
#
# Also writes agent-routing.md next to the agents directory: a routing section for
# CLAUDE.md, filtered to the agents installed. Importing it took correct automatic
# delegation from 8/20 to 20/20 in our live tests (see docs/TEST_RESULTS.md).
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src="$repo/.claude/agents"
dest="$HOME/.claude/agents"
mode=copy dry=0 uninstall=0 force=0 routing=1 scope=user
categories=() only=""

usage() { sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while (($#)); do
  case "$1" in
    --link) mode=link ;;
    --project) dest="$(cd "${2:?--project needs a directory}" && pwd)/.claude/agents"; scope=project; shift ;;
    --category) categories+=("${2:?--category needs a name}"); shift ;;
    --only) only="${2:?--only needs a list}"; shift ;;
    --dry-run) dry=1 ;;
    --force) force=1 ;;
    --no-routing) routing=0 ;;
    --uninstall) uninstall=1 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown option: $1" >&2; usage 1 ;;
  esac
  shift
done

run() { if ((dry)); then echo "would: $*"; else "$@"; fi; }

mapfile -t files < <(find "$src" -name '*.md' -type f | sort)
selected=()
for f in "${files[@]}"; do
  name="$(basename "$f" .md)"
  cat="$(basename "$(dirname "$f")")"
  if ((${#categories[@]})) && [[ ! " ${categories[*]} " == *" $cat "* ]]; then continue; fi
  if [[ -n "$only" ]] && [[ ! ",$only," == *",$name,"* ]]; then continue; fi
  selected+=("$f")
done
((${#selected[@]})) || { echo "no agents matched" >&2; exit 1; }

run mkdir -p "$dest"
installed=0 skipped=0
for f in "${selected[@]}"; do
  target="$dest/$(basename "$f")"
  if ((uninstall)); then
    if [[ -L "$target" && "$(readlink "$target")" == "$f" ]] || { [[ -f "$target" ]] && cmp -s "$f" "$target"; }; then
      run rm -f "$target"; installed=$((installed + 1))
    fi
    continue
  fi
  if [[ -e "$target" || -L "$target" ]] && ((!force)) && ! cmp -s "$f" "$target"; then
    echo "skip (exists and differs, use --force): $target" >&2; skipped=$((skipped + 1)); continue
  fi
  if [[ $mode == link ]]; then run ln -sfn "$f" "$target"; else run cp "$f" "$target"; fi
  installed=$((installed + 1))
done

verb=$([[ $uninstall == 1 ]] && echo removed || echo installed)
msg="$verb $installed agent(s) in $dest"
((skipped)) && msg+=" ($skipped skipped)"
echo "$msg"

# Routing section for CLAUDE.md, limited to the selected agents.
routing_file="$(dirname "$dest")/agent-routing.md"
marker="Generated by scripts/gen_catalog.py"
if ((uninstall)); then
  if [[ -f "$routing_file" ]] && grep -qF "$marker" "$routing_file"; then run rm -f "$routing_file"; fi
  exit 0
fi
((routing)) || exit 0
names=()
for f in "${selected[@]}"; do names+=("$(basename "$f" .md)"); done
filtered="$(awk -v keep="$(printf '%s\n' "${names[@]}")" '
  BEGIN { n = split(keep, k, "\n"); for (i = 1; i <= n; i++) want["`" k[i] "`"] = 1 }
  /^- `/ { if (want[$2]) print; next }
  { print }' "$repo/docs/ROUTING.md")"
if ((dry)); then echo "would: write $routing_file"; else printf '%s\n' "$filtered" > "$routing_file"; fi
if [[ $scope == user ]]; then
  import='@~/.claude/agent-routing.md' claude_md='~/.claude/CLAUDE.md'
else
  import='@.claude/agent-routing.md' claude_md="$(dirname "$(dirname "$dest")")/CLAUDE.md"
fi
echo "wrote $routing_file"
echo "For reliable automatic delegation, add this line to $claude_md:"
echo "  $import"
