#!/usr/bin/env python3
"""Regenerate derived files from agent frontmatter.

* README.md: everything between <!-- catalog:start --> and <!-- catalog:end -->.
* .claude-plugin/plugin.json: the `agents` list (plugin manifests must list each
  agent file individually; directories are not scanned recursively).
* docs/ROUTING.md: a routing section to import into a project's CLAUDE.md.

Use --check to fail (exit 1) if either file is out of date instead of writing.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / ".claude" / "agents"
README = ROOT / "README.md"
PLUGIN = ROOT / ".claude-plugin" / "plugin.json"
ROUTING = ROOT / "docs" / "ROUTING.md"
START, END = "<!-- catalog:start -->", "<!-- catalog:end -->"

CATEGORY_TITLES = {
    "review": "Code review & auditing",
    "testing": "Testing",
    "debugging": "Debugging & diagnosis",
    "architecture": "Architecture & refactoring",
    "docs": "Documentation",
    "languages": "Language & framework specialists",
    "data": "Data & databases",
    "devops": "DevOps, cloud & operations",
    "git": "Git & pull-request workflow",
    "ai": "AI engineering & Claude Code",
    "compliance": "Compliance & regulated software",
    "product": "Product & requirements",
    "research": "Research",
}


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    return yaml.safe_load(text.split("---", 2)[1])


def first_sentence(desc: str) -> str:
    desc = " ".join(desc.split())
    for sep in (". Use ", ". Not ", ". MUST"):
        if sep in desc:
            return desc.split(sep)[0] + "."
    return desc


def build() -> str:
    by_cat: dict[str, list[tuple[str, dict]]] = {}
    for f in sorted(AGENTS.rglob("*.md")):
        by_cat.setdefault(f.parent.name, []).append((f.relative_to(ROOT).as_posix(), frontmatter(f)))
    total = sum(len(v) for v in by_cat.values())
    order = [c for c in CATEGORY_TITLES if c in by_cat] + sorted(set(by_cat) - set(CATEGORY_TITLES))
    lines = [f"**{total} agents** in {len(by_cat)} categories.", ""]
    for cat in order:
        lines += [f"### {CATEGORY_TITLES.get(cat, cat.title())}", "",
                  "| Agent | What it does | Model | Access |", "| --- | --- | --- | --- |"]
        for rel, fm in sorted(by_cat[cat], key=lambda x: x[1]["name"]):
            tools = [t.strip() for t in fm.get("tools", "").split(",")] if isinstance(fm.get("tools"), str) else fm.get("tools", [])
            access = "read/write" if {"Write", "Edit"} & set(tools) else "read-only"
            if {"WebSearch", "WebFetch"} & set(tools):
                access += " + web"
            desc = first_sentence(fm["description"]).replace("|", "\\|")
            lines.append(f"| [`{fm['name']}`]({rel}) | {desc} | {fm.get('model', 'inherit')} | {access} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


SENTENCE_END = r"\.(?=\s+[A-Z]|\s*$)"  # a period that ends a sentence, not one inside CLAUDE.md


def when_clause(desc: str) -> str:
    """The routing trigger of a description: its 'Use ...' sentence, else the first one."""
    desc = " ".join(desc.split())
    m = re.search(r"Use (PROACTIVELY |proactively )?(when|after|before|to|for)\b.*?" + SENTENCE_END, desc)
    return m.group(0) if m else first_sentence(desc)


def headline(desc: str) -> str:
    """What the agent does, in a few words: the first sentence up to its first colon or parenthesis."""
    first = re.split(SENTENCE_END, " ".join(desc.split()), maxsplit=1)[0]
    head = re.split(r":| \(", first, maxsplit=1)[0].strip()
    return head if len(head) <= 110 else head[:107].rsplit(" ", 1)[0] + "..."


def build_routing() -> str:
    lines = [
        "<!-- Generated by scripts/gen_catalog.py; do not edit by hand. -->",
        "# Subagent routing",
        "",
        "Delegate to a specialized subagent (Agent tool) whenever a request matches one of",
        "these triggers, instead of doing the work in the main conversation. Delegation keeps",
        "verbose output out of this context and applies the agent's checklist and report",
        "format. Do small, obvious edits yourself. Name the agent when the user does.",
        "",
    ]
    for f in sorted(AGENTS.rglob("*.md")):
        fm = frontmatter(f)
        lines.append(f"- `{fm['name']}` ({headline(fm['description'])}): {when_clause(fm['description'])}")
    return "\n".join(lines) + "\n"


def build_plugin(current: str) -> str:
    manifest = json.loads(current)
    manifest["agents"] = [f"./{f.relative_to(ROOT).as_posix()}" for f in sorted(AGENTS.rglob("*.md"))]
    return json.dumps(manifest, indent=2) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    readme = README.read_text(encoding="utf-8")
    if START not in readme or END not in readme:
        sys.exit(f"README.md must contain {START} and {END}")
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    outputs = {README: (readme, f"{head}{START}\n{build()}{END}{tail}")}
    plugin = PLUGIN.read_text(encoding="utf-8")
    outputs[PLUGIN] = (plugin, build_plugin(plugin))
    outputs[ROUTING] = (ROUTING.read_text(encoding="utf-8") if ROUTING.exists() else "", build_routing())

    stale = [p for p, (old, new) in outputs.items() if old != new]
    if check:
        for p in stale:
            print(f"{p.relative_to(ROOT)} is out of date; run `make catalog`", file=sys.stderr)
        return 1 if stale else 0
    for p in stale:
        p.write_text(outputs[p][1], encoding="utf-8")
        print(f"updated {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
